// 4613732
public class Dinh2 {
     /*
     * Each new term in the Fibonacci Sequence is generated by adding the previous two terms. 
     * By stating with 1 and 2, the first 10 terms will be:
     * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89
     * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
     * find the sum of the even-valued terms.
     * 
     * Solution: 4613732
     */

     /*
      * loop that will go through every number in the fib sequence 
      * stop loop when the current fib number is greater than limit 
      * check if the sum of int n passed through is an even number (%2)
      * add the fib number to the sum if even
      */
    public static void main(String[] args) {
        int limit = 4000000;
        int prev = 1;          // previous Fib number 
        int curr = 2;          // current Fib number 
        int sum = 0;
        
        while (curr <= limit){
            /*
             * while loop runs if the current number is less or equal to 4 million
             * if the current number is even, add to the sum
             */
            if (curr % 2 == 0){
                sum += curr;
            }

            // generate next fib number
            int next = prev + curr;
            prev = curr;
            curr = next;
        }
    
        System.out.println(sum);
    }
}
