// 76576500
public class Dinh12 {
    /**
     * The sequence of triangle numbers is generated by adding the natural numbers.
     * So the 7th triangle number would be:
     * 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. 
     * The first ten terms would be:
     * 1,3,6,10,15,21,28,36,45,55,…
     * 
     * Let us list the factors of the first seven triangle numbers:
     * 𝟏:1
     * 𝟑:1,3
     * 𝟔:1,2,3,6
     * 𝟏𝟎:1,2,5,10
     * 𝟏𝟓:1,3,5,15
     * 𝟐𝟏:1,3,7,21
     * 𝟐𝟖:1,2,4,7,14,28
     * 
     * We can see that 28
     * is the first triangle number to have over five divisors.
     * 
     * What is the value of the first triangle number to have over five hundred
     * divisors?
     */

    public static void main(String[] args) {
        /**
         * loop that runs through every number
         * check that number to see if it is a triangle number
         * formula: (n * (n + 1)) / 2
         * 
         * if it is a triangle number, check how many divisors it has
         */

        int triangleNumber = 0; // result of triangle number formula
        int num = 0;  // tracks triangle number
        int triDivisorCount = 0; // count of divisors the triangle number has
        
        // loop runs through every number until 500
        while (triDivisorCount <= 500) {
            // loop increments num and calculates triangle number
            num++;
            triangleNumber = (num * (num + 1)) / 2;
            // loop checks every number from 1 up to the square root of the triangle number
            // sqrt because divisors come in pairs
            // if i divides the number, then (triangleNumber / i) also divides the number (divisor)
            triDivisorCount = 0;
            for (int i = 1; i <= Math.sqrt(triangleNumber); i++) {
                if (triangleNumber % i == 0) {
                    triDivisorCount += 2; // i and triangleNumber / i
                }
            }

        }
        System.out.println(triangleNumber);
    }
}
